name: Anything

on:
  # schedule:
  #   - cron: "*/2 * * * *"

  workflow_dispatch:

  push:
    branches:
      - "*"

  pull_request:
    branches:
      - master

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
      - name: Event context
        run: echo $EVENT_CONTEXT
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
      - name: Get checkout ref
        run: |
          if [ $IS_SCHEDULED == 'true' ]; then checkout_ref=$CRON_REF; else checkout_ref=$DISPATCH_REF; fi
          echo '-------------------------' $IS_SCHEDULED
          echo '-------------------------' $checkout_ref
          echo "::set-output name=checkout_ref::$(echo $checkout_ref)"
        env:
          IS_SCHEDULED: ${{ github.event.schedule != '' }}
          DISPATCH_REF: ${{ github.ref }}
          CRON_REF: release
        id: get_checkout_ref
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_checkout_ref.outputs.checkout_ref }}
      - name: Get branch slugs
        uses: rlespinasse/github-slug-action@v3.x
      - name: Long running task 1
        run: exit 0
      - name: Long running task 2
        run: exit 0
      - name: Get PR number
        if: ${{ always() }}
        id: get_pr
        uses: jwalton/gh-find-current-pr@v1
      - name: Comment on PR
        if: ${{ (failure() || success()) && steps.get_pr.outputs.pr != ''}}
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.get_pr.outputs.pr }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '[This](https://github.com/iamkenos/actions/actions/runs/${{ github.run_id }}) workflow ${{ fromJSON('{ "failure":"failed", "success":"passed" }')[job.status] }} on ${{ github.sha }} '
            })
